export const spawnGroups = {
  insects: [
    "BP_Bug_BeetleC_C",
    "BP_Bug_ButterflyC_C",
    "BP_Bug_CricketC_C",
    "BP_Bug_CricketU_C",
    "BP_Bug_DragonflyC_C",
    "BP_Bug_DragonflyR_C",
    "BP_Bug_LadybugR_C",
    "BP_Bug_MantisU_C",
    "BP_Bug_MothC_C",
    "BP_Bug_PedeU_C",
  ],
  foraging: [
    "BP_Gatherable_Elouisa_Dropoff_C",
    "BP_Gatherable_MushroomR_C",
    "BP_Moss_EmeraldCarpet_C",
    "BP_ShrubChoppable_Bush_C",
    "BP_Spiced_Sprouts_C",
    "BP_SundropLillies_C",
    "BP_TreeChoppable_Birch_Large_C",
    "BP_TreeChoppable_Birch_Medium_C",
    "BP_TreeChoppable_Birch_Sapling_C",
    "BP_TreeChoppable_Birch_Small_C",
    "BP_TreeChoppable_Oak_Large_C",
    "BP_TreeChoppable_Oak_Medium_C",
    "BP_TreeChoppable_Oak_Sapling_C",
    "BP_TreeChoppable_Oak_Small_C",
    "BP_WaterFlower_C",
    "BP_WildGarlic_C",
  ],
  mining: [
    "BP_Mining_Clay_C",
    "BP_Mining_Copper_Large_C",
    "BP_Mining_Copper_Medium_C",
    "BP_Mining_Copper_Small_C",
    "BP_Mining_Stone_Large_C",
    "BP_Mining_Stone_Medium_C",
    "BP_Mining_Stone_Small_C",
  ],
  hunting: [
    "BP_ValeriaHuntingCreature_Cearnuk_T1_C",
    "BP_ValeriaHuntingCreature_Cearnuk_T2_C",
    "BP_ValeriaHuntingCreature_Chapaa_T1_C",
    "BP_ValeriaHuntingCreature_Chapaa_T2_C",
  ],
  fishing: [
    "BP_WaterPlane_Fishing_LakeVillage_SQ_C",
    "BP_WaterPlane_Fishing_RiverVillage_SQ_C",
  ],
};
