export const landmark = [
  {
    id: "MapMarker_Apothecary",
    name: "DefaultSceneRoot",
    x: -556.85547,
    y: 18259.395,
  },
  {
    id: "MapMarker_Blacksmith",
    name: "DefaultSceneRoot",
    x: 2320,
    y: 7030,
  },
  {
    id: "MapMarker_CityHall",
    name: "DefaultSceneRoot",
    x: 7490,
    y: 2570,
  },
  {
    id: "MapMarker_DragonShrine",
    name: "DefaultSceneRoot",
    x: 33740,
    y: -22330,
  },
  {
    id: "MapMarker_FamilyFarm",
    name: "DefaultSceneRoot",
    x: -29530,
    y: -3340,
  },
  {
    id: "MapMarker_FurnitureStore",
    name: "DefaultSceneRoot",
    x: 2890,
    y: -1790,
  },
  {
    id: "MapMarker_GeneralStore",
    name: "DefaultSceneRoot",
    x: 780,
    y: -570,
  },
  {
    id: "MapMarker_Library",
    name: "DefaultSceneRoot",
    x: 5290,
    y: -4190,
  },
  {
    id: "MapMarker_MayorsEstate",
    name: "DefaultSceneRoot",
    x: 13500,
    y: 20930,
  },
  {
    id: "MapMarker_PhoenixFalls",
    name: "DefaultSceneRoot",
    x: 670,
    y: -35620,
  },
  {
    id: "MapMarker_RemembranceGarden",
    name: "DefaultSceneRoot",
    x: -7330,
    y: 27000,
  },
  {
    id: "MapMarker_Tailor",
    name: "DefaultSceneRoot",
    x: -2350,
    y: 1070,
  },
  {
    id: "MapMarker_Tavern",
    name: "DefaultSceneRoot",
    x: -1360,
    y: 5170,
  },
];
