export const landmark = [
  {
    id: "MapMarker_AncientRuins",
    mapName: "bahari-bay",
    x: 55320,
    y: -48900,
  },
  {
    id: "MapMarker_MiningFamily",
    mapName: "bahari-bay",
    x: 67325,
    y: -22823,
  },
  {
    id: "MapMarker_OldLighthouse",
    mapName: "bahari-bay",
    x: 163430,
    y: -55440,
  },
  {
    id: "MapMarker_Tamalas",
    mapName: "bahari-bay",
    x: 78810,
    y: -108283.5,
  },
  {
    id: "MapMarker_Apothecary",
    mapName: "kilima-valley",
    x: -556.86,
    y: 18259.4,
  },
  {
    id: "MapMarker_Blacksmith",
    mapName: "kilima-valley",
    x: 2320,
    y: 7030,
  },
  {
    id: "MapMarker_CityHall",
    mapName: "kilima-valley",
    x: 7490,
    y: 2570,
  },
  {
    id: "MapMarker_DragonShrine",
    mapName: "kilima-valley",
    x: 33740,
    y: -22330,
  },
  {
    id: "MapMarker_FamilyFarm",
    mapName: "kilima-valley",
    x: -29530,
    y: -3340,
  },
  {
    id: "MapMarker_FurnitureStore",
    mapName: "kilima-valley",
    x: 2890,
    y: -1790,
  },
  {
    id: "MapMarker_GeneralStore",
    mapName: "kilima-valley",
    x: 780,
    y: -570,
  },
  {
    id: "MapMarker_Library",
    mapName: "kilima-valley",
    x: 5290,
    y: -4190,
  },
  {
    id: "MapMarker_MayorsEstate",
    mapName: "kilima-valley",
    x: 13500,
    y: 20930,
  },
  {
    id: "MapMarker_PhoenixFalls",
    mapName: "kilima-valley",
    x: 670,
    y: -35620,
  },
  {
    id: "MapMarker_RemembranceGarden",
    mapName: "kilima-valley",
    x: -7330,
    y: 27000,
  },
  {
    id: "MapMarker_Tailor",
    mapName: "kilima-valley",
    x: -2350,
    y: 1070,
  },
  {
    id: "MapMarker_Tavern",
    mapName: "kilima-valley",
    x: -1360,
    y: 5170,
  },
];
